package com.tewe.nrftw.items

import com.tewe.nrftw.Gem
import com.tewe.nrftw.GemEffect
import com.tewe.nrftw.ItemSlot.*

val gems = List(
  Gem(
    "ca",
    "Chipped Amethyst",
    "/images/gem-chippedAmethyst.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Plague Damage Infusion", extra = true),
      GemEffect(ShieldSlot, "Deal 5%-15% Plague Damage on Block"),
      GemEffect(BowSlot, "Plague Damage Infusion", extra = true),
      GemEffect(ArmorSlot, "Plague Resistance increased by 6%-20%"),
      GemEffect(HelmetSlot, "Infection Buildup increased by 4%-15%"),
      GemEffect(PantsSlot, "Plague Resistance increased by 6%-20%"),
      GemEffect(GlovesSlot, "Infection Buildup increased by 4%-15%"),
    ),
  ),
  Gem(
    "cbp",
    "Chipped Black Pearl",
    "/images/gem-chippedBlackPearl.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Healing increased by 4%-15%", extra = true),
      GemEffect(ShieldSlot, "Healing increased by 3%-10%"),
      GemEffect(BowSlot, "Healing increased by 3%-10%"),
      GemEffect(ArmorSlot, "Healing increased by 4%-15%", extra = true),
      GemEffect(HelmetSlot, "Healing increased by 3%-10%"),
      GemEffect(PantsSlot, "Healing increased by 3%-10%"),
      GemEffect(GlovesSlot, "Healing increased by 3%-10%"),
    ),
  ),
  Gem(
    "cbs",
    "Chipped Blood Stone",
    "/images/gem-chippedBloodStone.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Lifesteal increased by 3%-10%", extra = true),
      GemEffect(ShieldSlot, "Lifesteal increased by 2%-5%"),
      GemEffect(BowSlot, "Lifesteal increased by 2%-5%"),
      GemEffect(ArmorSlot, "Regainable Health increased by 5%-15%"),
      GemEffect(HelmetSlot, "Regainable Health increased by 5%-15%"),
      GemEffect(PantsSlot, "Regainable Health increased by 5%-15%"),
      GemEffect(GlovesSlot, "Regainable Health increased by 10%-25%", extra = true),
    ),
  ),
  Gem(
    "cd",
    "Chipped Diamond",
    "/images/gem-chippedDiamond.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Experience Gain increased by 3%-10%"),
      GemEffect(HelmetSlot, "Experience Gain increased by 3%-10%"),
      GemEffect(PantsSlot, "Experience Gain increased by 3%-10%"),
      GemEffect(GlovesSlot, "Experience Gain increased by 3%-10%"),
    ),
  ),
  Gem(
    "cdn",
    "Chipped Dianite",
    "/images/gem-chippedDianite.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Focus Cost decreased by 2%-5%"),
      GemEffect(HelmetSlot, "Focus Cost decreased by 2%-5%"),
      GemEffect(PantsSlot, "Focus Cost decreased by 2%-5%"),
      GemEffect(GlovesSlot, "Focus Cost decreased by 3%-10%", extra = true),
    ),
  ),
  Gem(
    "ce",
    "Chipped Emerald",
    "/images/gem-chippedEmerald.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Max Stamina increased by 4%-15%", extra = true),
      GemEffect(ShieldSlot, "Max Stamina increased by 3%-10%"),
      GemEffect(BowSlot, "Max Stamina increased by 3%-10%"),
      GemEffect(ArmorSlot, "Max Stamina increased by 3%-10%"),
      GemEffect(HelmetSlot, "Max Stamina increased by 3%-10%"),
      GemEffect(PantsSlot, "Max Stamina increased by 4%-15%", extra = true),
      GemEffect(GlovesSlot, "Max Stamina increased by 3%-10%"),
    ),
  ),
  Gem(
    "tf",
    "Tiny Fang",
    "/images/gem-tinyFang.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Attack Stamina Cost decreased by 7%-15%", extra = true),
      GemEffect(ShieldSlot, "Parry Stamina Cost decreased by 9%-30%", extra = true),
      GemEffect(BowSlot, "Dodge Stamina Cost decreased by 7%-25%", extra = true),
      GemEffect(ArmorSlot, "Stamina Cost decreased by 2%-6%"),
      GemEffect(HelmetSlot, "Stamina Cost decreased by 2%-6%"),
      GemEffect(PantsSlot, "Stamina Cost decreased by 3%-10%", extra = true),
      GemEffect(GlovesSlot, "Stamina Cost decreased by 2%-6%"),
    ),
  ),
  Gem(
    "tft",
    "Tiny Feather",
    "/images/gem-tinyFeather.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Item Weight decreased by 4%-15%"),
      GemEffect(ShieldSlot, "Item Weight decreased by 4%-15%"),
      GemEffect(BowSlot, "Item Weight decreased by 4%-15%"),
      GemEffect(ArmorSlot, "Item Weight decreased by 4%-15%"),
      GemEffect(HelmetSlot, "Item Weight decreased by 4%-15%"),
      GemEffect(PantsSlot, "Item Weight decreased by 4%-15%"),
      GemEffect(GlovesSlot, "Item Weight decreased by 4%-15%"),
    ),
  ),
  Gem(
    "cg",
    "Chipped Granite",
    "/images/gem-chippedGranite.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Poise Defense increased by 1-3"),
      GemEffect(HelmetSlot, "Poise Defense increased by 1-3"),
      GemEffect(PantsSlot, "Poise Defense increased by 1-3"),
      GemEffect(GlovesSlot, "Poise Defense increased by 1-3"),
    ),
  ),
  Gem(
    "cj",
    "Chipped Jade",
    "/images/gem-chippedJade.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Stamina Recovery increased by 4%-12%"),
      GemEffect(HelmetSlot, "Stamina Recovery increased by 4%-12%"),
      GemEffect(PantsSlot, "Stamina Recovery increased by 4%-12%"),
      GemEffect(GlovesSlot, "Stamina Recovery increased by 6%-20%", extra = true),
    ),
  ),
  Gem(
    "cjw",
    "Chipped Jewel",
    "/images/gem-chippedJewel.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Max Focus increased by 4%-15%", extra = true),
      GemEffect(ShieldSlot, "Max Focus increased by 3%-10%"),
      GemEffect(BowSlot, "Max Focus increased by 3%-10%"),
      GemEffect(ArmorSlot, "Max Focus increased by 3%-10%"),
      GemEffect(HelmetSlot, "Max Focus increased by 4%-15%", extra = true),
      GemEffect(PantsSlot, "Max Focus increased by 3%-10%"),
      GemEffect(GlovesSlot, "Max Focus increased by 3%-10%"),
    ),
  ),
  Gem(
    "cm",
    "Chipped Marble",
    "/images/gem-chippedMarble.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Max Health increased by 4%-15%", extra = true),
      GemEffect(ShieldSlot, "Max Health increased by 3%-10%"),
      GemEffect(BowSlot, "Max Health increased by 3%-10%"),
      GemEffect(ArmorSlot, "Max Health increased by 4%-15%", extra = true),
      GemEffect(HelmetSlot, "Max Health increased by 3%-10%"),
      GemEffect(PantsSlot, "Max Health increased by 3%-10%"),
      GemEffect(GlovesSlot, "Max Health increased by 3%-10%"),
    ),
  ),
  Gem(
    "cmr",
    "Chipped Meteorite",
    "/images/gem-chippedMeteorite.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Elemental Damage Taken decreased by 2%-5%"),
      GemEffect(HelmetSlot, "Elemental Damage Taken decreased by 2%-5%"),
      GemEffect(PantsSlot, "Elemental Damage Taken decreased by 2%-5%"),
      GemEffect(GlovesSlot, "Elemental Damage Taken decreased by 2%-5%"),
    ),
  ),
  Gem(
    "cms",
    "Chipped Moon Stone",
    "/images/gem-chippedMoonStone.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Regenerate Focus in Combat"),
      GemEffect(HelmetSlot, "Regenerate Focus in Combat"),
      GemEffect(PantsSlot, "Regenerate Focus in Combat"),
      GemEffect(GlovesSlot, "Regenerate Focus in Combat"),
    ),
  ),
  Gem(
    "cq",
    "Chipped Quartz",
    "/images/gem-chippedQuartz.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Electric Damage Infusion", extra = true),
      GemEffect(ShieldSlot, "Deal 5%-15% Electric Damage on Block"),
      GemEffect(BowSlot, "Electric Damage Infusion", extra = true),
      GemEffect(ArmorSlot, "Electric Resistance increased by 10%-20%"),
      GemEffect(HelmetSlot, "Shock Buildup increased by 4%-15%"),
      GemEffect(PantsSlot, "Electric Resistance increased by 10%-20%"),
      GemEffect(GlovesSlot, "Shock Buildup increased by 4%-15%"),
    ),
  ),
  Gem(
    "cr",
    "Chipped Ruby",
    "/images/gem-chippedRuby.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Heat Damage Infusion", extra = true),
      GemEffect(ShieldSlot, "Deal 5%-15% Heat Damage on Block"),
      GemEffect(BowSlot, "Heat Damage Infusion", extra = true),
      GemEffect(ArmorSlot, "Heat Resistance increased by 10%-20%"),
      GemEffect(HelmetSlot, "Burn Buildup increased by 4%-15%"),
      GemEffect(PantsSlot, "Heat Resistance increased by 10%-20%"),
      GemEffect(GlovesSlot, "Burn Buildup increased by 4%-15%"),
    ),
  ),
  Gem(
    "cs",
    "Chipped Sapphire",
    "/images/gem-chippedSapphire.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Cold Damage Infusion", extra = true),
      GemEffect(ShieldSlot, "Deal 5%-15% Cold Damage on Block"),
      GemEffect(BowSlot, "Cold Damage Infusion", extra = true),
      GemEffect(ArmorSlot, "Cold Resistance increased by 10%-20%"),
      GemEffect(HelmetSlot, "Frost Buildup increased by 4%-15%"),
      GemEffect(PantsSlot, "Cold Resistance increased by 10%-20%"),
      GemEffect(GlovesSlot, "Frost Buildup increased by 4%-15%"),
    ),
  ),
  Gem(
    "cse",
    "Chipped Shield Emblem",
    "/images/gem-chippedShieldEmblem.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Physical Damage Taken decreased by 2%-5%"),
      GemEffect(HelmetSlot, "Physical Damage Taken decreased by 2%-5%"),
      GemEffect(PantsSlot, "Physical Damage Taken decreased by 2%-5%"),
      GemEffect(GlovesSlot, "Physical Damage Taken decreased by 2%-5%"),
    ),
  ),
  Gem(
    "ss",
    "Small Skull",
    "/images/gem-smallSkull.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Regenerate Health in Combat"),
      GemEffect(HelmetSlot, "Regenerate Health in Combat"),
      GemEffect(PantsSlot, "Regenerate Health in Combat"),
      GemEffect(GlovesSlot, "Regenerate Health in Combat"),
    ),
  ),
  Gem(
    "csk",
    "Chipped Spike",
    "/images/gem-chippedSpike.png",
    gemEffects = List(
      GemEffect(WeaponSlot, "Physical Damage increased by 3%-10%", extra = true),
      GemEffect(ShieldSlot, "Physical Damage increased by 2%-5%"),
      GemEffect(BowSlot, "Physical Damage increased by 2%-5%"),
      GemEffect(ArmorSlot, "Armor increased by 4%-12%"),
      GemEffect(HelmetSlot, "Buildup Resistance increased by 4%-15%"),
      GemEffect(PantsSlot, "Armor increased by 4%-12%"),
      GemEffect(GlovesSlot, "Buildup Resistance increased by 4%-15%"),
    ),
  ),
  Gem(
    "ct",
    "Chipped Topaz",
    "/images/gem-chippedTopaz.png",
    gemEffects = List(
      GemEffect(ArmorSlot, "Focus Gain increased by 2%-6%"),
      GemEffect(HelmetSlot, "Focus Gain increased by 3%-10%", extra = true),
      GemEffect(PantsSlot, "Focus Gain increased by 2%-6%"),
      GemEffect(GlovesSlot, "Focus Gain increased by 2%-6%"),
    ),
  ),
)


