package com.tewe.nrftw.items

import com.tewe.nrftw.ItemRarity
import com.tewe.nrftw.RingData

val rings = List(
  RingData(
    "r_cr",
    "Crow Ring",
    ItemRarity.Plagued,
    "Description of Crow Ring",
    1,
    100,
    0.0,
    "/images/ring-crowRing.png",
    enchantments = List("Max Stamina Increased by 30-50%"),
    enchantDownsides = List("Drain Health in combat"),
  ),
  RingData(
    "r_fr",
    "Feather Ring",
    ItemRarity.Magic,
    "Description Feather Ring",
    1,
    100,
    0.0,
    "/images/ring-featherRing.png",
    List("Equip Load Increased by 10-20%"),
  ),
  RingData(
    "r_rr",
    "Rune Ring",
    ItemRarity.Plagued,
    "Description of Rune Ring",
    1,
    100,
    0.0,
    "/images/ring-runeRing.png",
    List("Rune Damage increased by 10%-30%"),
    enchantDownsides = List("Attack Damage decreased by 10%-20%"),
  ),
  RingData(
    "r_sr",
    "Solace Ring",
    ItemRarity.Magic,
    "Description of Solace Ring",
    1,
    100,
    0.0,
    "/images/ring-solaceRing.png",
    List("Regainable Health Increased by 10%-30%"),
  ),
  RingData(
    "r_str",
    "Stone Tusk Ring",
    ItemRarity.Magic,
    "Description of Stone Tusk Ring",
    1,
    100,
    0.0,
    "/images/ring-stoneTuskRing.png",
    List("Armor Increased by 25%"),
  ),
  RingData(
    "r_wr",
    "Woven Ring",
    ItemRarity.Magic,
    "Description of Woven Ring",
    1,
    100,
    0.0,
    "/images/ring-wovenRing.png",
    List("Endless Climbing"),
  ),
  RingData(
    "r_ar",
    "Agility Ring",
    ItemRarity.Magic,
    "Description of Agility Ring",
    1,
    100,
    0.0,
    "/images/ring-agilityRing.png",
    List(
      "Attack Stamina Cost Decreased by 20%",
      "Movement Speed Increased by 10%",
      "Sprint Stamina Cost Decreased by 25%",
    ),
  ),
  RingData(
    "r_boc",
    "Band of Calmness",
    ItemRarity.Magic,
    "Description of Band of Calmness",
    11,
    100,
    0.0,
    "/images/ring-bandOfCalmness.png",
    List("Focus Gain Increased by 25%", "Max Focus Increased by 50%"),
  ),
  RingData(
    "r_gb",
    "Golden Band",
    ItemRarity.Magic,
    "Description of Golden Band",
    11,
    100,
    0.0,
    "/images/ring-goldenBand.png",
    List("Increased Experience by 5-10%"),
  ),
  RingData(
    "r_jr",
    "Jade Ring",
    ItemRarity.Magic,
    "Description of Jade Ring",
    11,
    100,
    0.0,
    "/images/ring-jadeRing.png",
    List("Gain 3%-6% Stamina on Damage Dealt"),
  ),
  RingData(
    "r_pr",
    "Plagued Ring",
    ItemRarity.Plagued,
    "Description of Plagued Ring",
    11,
    100,
    0.0,
    "/images/ring-plaguedRing.png",
    List("Lifesteal Increased by 20% at Low Health"),
    enchantDownsides = List("Max Health decreased by 20%"),
  ),
  RingData(
    "r_robr",
    "Ring of Broken Promises",
    ItemRarity.Plagued,
    "Description of Ring of Broken Promises",
    11,
    100,
    0.0,
    "/images/ring-ringOfBrokenPromises.png",
    List("Damage Dealt Increased by 10-20%"),
    enchantDownsides = List("Damage Taken Increased by 10-20%"),
  ),
  RingData(
    "r_fir",
    "Fierce Ring",
    ItemRarity.Magic,
    "Description of Fierce Ring",
    21,
    100,
    0.0,
    "/images/ring-fierceRing.png",
    List("Damage Increased by 8%-20% for 10 seconds after Damage Taken"),
  ),
  RingData(
    "r_sir",
    "Silver Ring",
    ItemRarity.Magic,
    "Description of Silver Ring",
    21,
    100,
    0.0,
    "/images/ring-silverRing.png",
    List("Deals 35% Damage on Parry"),
  ),
  RingData(
    "r_snr",
    "Snake Ring",
    ItemRarity.Plagued,
    "Description of Snake Ring",
    21,
    100,
    0.0,
    "/images/ring-snakeRing.png",
    List("Deals 25% Damage on Block"),
    enchantDownsides = List("Lose 6 Stamina on Block"),
  ),
  RingData(
    "r_tr",
    "Thistle Ring",
    ItemRarity.Plagued,
    "Description of Thistle Ring",
    21,
    100,
    0.0,
    "/images/ring-thistleRing.png",
    List("Deal 21%-25% Damage on Damage Taken"),
    enchantDownsides = List("Lose 8-6 Stamina on Damage Taken"),
  ),
  RingData(
    "r_wcr",
    "Willow Cap Ring",
    ItemRarity.Magic,
    "Description of Willow Cap Ring",
    21,
    100,
    0.0,
    "/images/ring-willowCapRing.png",
    List("Overall Speed increased by 15%"),
  ),
  RingData(
    "r_br",
    "Battlecry Ring",
    ItemRarity.Legendary,
    "Description of Battlecry Ring",
    0,
    100,
    0.0,
    "/images/ring-battlecryRing.png",
    List("Spend Health instead of Focus"),
    enchantDownsides = List("Cannot Lifesteal"),
  ),
  RingData(
    "r_rod",
    "Ring of Determination",
    ItemRarity.Legendary,
    "Description of Ring of Determination",
    0,
    100,
    0.0,
    "/images/ring-ringOfDetermination.png",
    List(
      "Spend Health if there is not enough Focus available",
      "Focus Cost decreased by up to 60% based on Missing Health",
    ),
  ),
  RingData(
    "r_scr",
    "Scarlet Ring",
    ItemRarity.Legendary,
    "Description of Scarlet Ring",
    0,
    100,
    0.0,
    "/images/ring-scarletRing.png",
    List("Swap Max Health and Max Focus"),
  ),
  RingData(
    "r_ser",
    "Serendipity Ring",
    ItemRarity.Legendary,
    "Description of Serendipity Ring",
    0,
    100,
    0.0,
    "/images/ring-serendipityRing.png",
    List("Food Healing is applied over time", "Healing increased by 18%-30%"),
  ),
)

